# Generated by Django 5.0.1 on 2024-01-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_guide_name_guide_first_name_guide_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
