# Generated by Django 5.0.1 on 2024-01-27 06:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_guide_name_guide_first_name_guide_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='guide',
            name='created',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='updated',
        ),
        migrations.AddField(
            model_name='guide',
            name='bio',
            field=models.TextField(default='enjoys adventure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guide')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.themepark')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='parks',
            field=models.ManyToManyField(to='base.themepark'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
