# Generated by Django 5.0.1 on 2024-01-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_guide_options_remove_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
