# Generated by Django 5.0.1 on 2024-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_rating_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('guides', models.ManyToManyField(related_name='guides', to='base.guide')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='parks',
            field=models.ManyToManyField(related_name='parks', to='base.park'),
        ),
    ]
