# Generated by Django 5.0.1 on 2024-01-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_park_guide_parks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='parks',
            field=models.ManyToManyField(null=True, related_name='parks', to='base.park'),
        ),
        migrations.AlterField(
            model_name='park',
            name='guides',
            field=models.ManyToManyField(null=True, related_name='guides', to='base.guide'),
        ),
        migrations.CreateModel(
            name='GuideParkRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.guide')),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.park')),
            ],
        ),
    ]
